version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0-jessie-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
  deploy:
    docker: 
      - image: circleci/node:10.15.0-jessie-browsers-legacy
    steps:
      - run:
          name: AWS EC2 deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@3.17.139.99 \
            "echo Start deploy && \
            cd ~/server && \
            git pull && \
            npm i && \
            npm run build && \
            pm2 stop build/server && \
            pm2 start build/server && \
            echo Deploy end"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build