version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: aws
          command: ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-17-139-99.us-east-2.compute.amazonaws.com "./deploy.sh"