version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0-jessie-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - deploy:
          name: AWS EC2 deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@18.191.6.154 \
            "echo Start deploy && \
            cd ~/server && \
            git pull && \
            yarn && \
            pm2 stop "server" && \
            PORT=8080 pm2 start server.js --name "server" && \
            echo Deploy end"
